name: Run Loggers

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  log-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Java & Scala
        uses: coursier/setup-action@v1
        with:
          jvm: 'temurin:17'
          apps: sbt

      - name: Log Date
        env:
          LOGGER: "date"
          LOG_PATH: "logs/dates.csv"
          RETENTION: "30"
        run: sbt run
        continue-on-error: true

      - name: Log Time
        env:
          LOGGER: "time"
          LOG_PATH: "logs/times.csv"
          RETENTION: "10"
          PARAM_TIMEZONE: "America/New_York"
        run: sbt run
        continue-on-error: true

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add logs/*
          git commit -m "Update log files with new entries"
        continue-on-error: true

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:main  # Push to the main branch
        continue-on-error: true